# Generated by Django 5.2.6 on 2025-09-13 19:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Groceries'), ('TRANSPORT', 'Transport'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER')),
                ('name_of_item', models.CharField(max_length=255)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='tracker_exp_user_id_2394ee_idx'), models.Index(fields=['category'], name='tracker_exp_categor_a11f14_idx'), models.Index(fields=['created_at'], name='tracker_exp_created_fc8f06_idx'), models.Index(fields=['user', 'category'], name='tracker_exp_user_id_8f1907_idx'), models.Index(fields=['user', 'created_at'], name='tracker_exp_user_id_db92fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_revenue', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='tracker_inc_user_id_3b61f2_idx'), models.Index(fields=['created_at'], name='tracker_inc_created_82be12_idx'), models.Index(fields=['user', 'created_at'], name='tracker_inc_user_id_ca3889_idx')],
            },
        ),
    ]
