# Generated by Django 5.2.6 on 2025-09-14 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='estimated_amount',
            new_name='estimated',
        ),
    ]
