# Generated by Django 5.2.6 on 2025-09-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_estimated_amount_expenditure_estimated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='estimated',
            new_name='amount',
        ),
    ]
