# Generated by Django 5.2.6 on 2025-09-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_estimated_expenditure_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food & Groceries'), ('TRANSPORT', 'Transport'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
