# Generated by Django 5.2.6 on 2025-09-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_expenditure_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='name_of_revenue',
            new_name='nameOfRevenue',
        ),
    ]
