# Generated by Django 5.2.6 on 2025-09-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_name_of_revenue_income_nameofrevenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='name_of_item',
            new_name='nameOfItem',
        ),
    ]
